const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
				"child":[
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"用户管理",
						"menuJump":"列表",
						"tableName":"yonghu"
					}
				],
				"menu":"用户管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"我的文件管理",
						"menuJump":"列表",
						"tableName":"wodewenjian"
					},
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"文件类型管理",
						"menuJump":"列表",
						"tableName":"leixing"
					}
				],
				"menu":"我的文件管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"分享文件管理",
						"menuJump":"列表",
						"tableName":"fenxiang"
					}
				],
				"menu":"分享文件管理"
			}
             ,{
                 "child":[
                     {
                         "buttons":[
                             "查看",
                             "新增",
                             "修改",
                             "删除"
                         ],
                         "menu":"公告管理",
                         "menuJump":"列表",
                         "tableName":"news"
                     }
                 ],
                 "menu":"公告管理"
             }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
  
    {
        "backMenu":[
           {
           	"child":[
           		{
           			"buttons":[
           				"查看",
           				"新增",
						"分享文件",
						"取消分享",
						"修改",
           				"删除"
           			],
           			"menu":"我的文件管理",
           			"menuJump":"列表",
           			"tableName":"wodewenjian"
           		}
           	],
           	"menu":"我的文件管理"
           }
           ,{
           	"child":[
           		{
           			"buttons":[
           				"查看"
           			],
           			"menu":"分享文件管理",
           			"menuJump":"列表",
           			"tableName":"fenxiang"
           		}
           	],
           	"menu":"分享文件管理"
           }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
	
	
	}
}
export default menu;
